# Keep serializer companions generated by the kotlinx.serialization compiler plugin.
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**

-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
    static <1>$Companion Companion;
}

-if @kotlinx.serialization.Serializable class ** {
    static **$* *;
}
-keepclassmembers class <2>$<3> {
    kotlinx.serialization.KSerializer serializer(...);
}

-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
    *** Companion;
}
-keepclasseswithmembers class ** {
    kotlinx.serialization.KSerializer serializer(...);
}

# ══════════════════════════════════════════════════════════════════════════════
#  GRAY PART
# ══════════════════════════════════════════════════════════════════════════════

# ══ Attribute preservation ═════════════════════════════════════════════════
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable
-keepattributes EnclosingMethod
-keepattributes InnerClasses

# ══ WebView JS bridge ══════════════════════════════════════════════════════
# The @JavascriptInterface methods are called by name from JS; R8 must not
# rename them or strip them.
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

# ══ Firebase ═══════════════════════════════════════════════════════════════
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.firebase.**

# ══ AppsFlyer ══════════════════════════════════════════════════════════════
-keep class com.appsflyer.** { *; }
-keep class com.android.installreferrer.** { *; }
-dontwarn com.appsflyer.**

# ══ OkHttp ═════════════════════════════════════════════════════════════════
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn org.conscrypt.**
-keep class okhttp3.** { *; }

# ══ Security-crypto ═══════════════════════════════════════════════════════
-keep class androidx.security.crypto.** { *; }

# ══ Gray entry classes + native game host ══════════════════════════════════
# rebrand.py updates the gray package paths here when it renames the flow.
-keep class bp.goalsgames.blockbalance.attr.FcmReceiver
-keep class bp.goalsgames.blockbalance.net.LaunchGate
-keep class bp.goalsgames.blockbalance.net.OrbitApp
-keep class bp.goalsgames.blockbalance.StageActivity

# ══ Strip debug-level logs in release ══════════════════════════════════════
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
}

# UNIQUE:DICTIONARY_WIRING:BEGIN
# Per-project R8 dictionaries — generated by tools/uniqueness_dictionaries.py.
# Refresh them by running the script again after `gradlew graySeed`.
-classobfuscationdictionary   proguard-dict/class-dictionary.txt
-obfuscationdictionary        proguard-dict/obf-dictionary.txt
-packageobfuscationdictionary proguard-dict/package-dictionary.txt

# Rename resources referenced from the manifest / XML so that after
# R8 the file names in the APK do not line up with any prior build.
-adaptresourcefilenames    **.properties,**.xml,**.png,**.webp,**.json,**.html
-adaptresourcefilecontents **.properties,**.xml,**.json,META-INF/MANIFEST.MF

# Move package hierarchy under a single random root — R8 collapses
# every non-kept package into `a.b.c` etc. from the package dict, so
# two projects share zero package paths after minify.
-repackageclasses
-allowaccessmodification
# UNIQUE:DICTIONARY_WIRING:END
