// UNIQUE:NATIVE_STUB:BEGIN
//
// Regenerated by `tools/uniqueness_native.py` on every seed rotation. Do NOT
// hand-edit — the tool overwrites the entire file. The unique per-project
// content lives in the constants below; the function body is a byte-XOR
// routine that is intentionally boring so R8 / a native code scanner has
// nothing distinguishing to key on except the numbers.
//
// If gray.enableNativeStub = false, the AGP externalNativeBuild block is
// disabled and this file is not compiled.

#include <jni.h>
#include <cstddef>
#include <cstdint>

namespace {

// The two constants below are the entire fingerprint of this file — they are
// regenerated per seed by `tools/uniqueness_native.py`. Leaving them at the
// defaults would land the same .so in every project.
constexpr uint32_t kPattern = 0x80BECA4Fu;
constexpr uint32_t kRotate  = 5u;

inline uint32_t churn_word(uint32_t x, uint32_t salt) {
    uint32_t r = x ^ salt ^ kPattern;
    r = (r << kRotate) | (r >> (32u - kRotate));
    return r * 0x80D77441u + 0xEDAFA9FAu;
}

}  // namespace

extern "C" JNIEXPORT jint JNICALL
Java_bp_goalsgames_blockbalance_nativez_EntropyStub_nativeChurn(
        JNIEnv* env, jclass, jbyteArray input, jlong salt) {
    if (input == nullptr) return 0;
    const jsize length = env->GetArrayLength(input);
    if (length <= 0) return 0;
    jbyte* bytes = env->GetByteArrayElements(input, nullptr);
    if (bytes == nullptr) return 0;

    uint32_t acc = static_cast<uint32_t>(salt);
    const jsize word_count = length / 4;
    auto* words = reinterpret_cast<uint32_t*>(bytes);
    for (jsize i = 0; i < word_count; ++i) {
        acc = churn_word(words[i], acc);
    }
    // Tail bytes.
    uint32_t tail = 0;
    for (jsize i = word_count * 4; i < length; ++i) {
        tail = (tail << 8u) | static_cast<uint32_t>(static_cast<uint8_t>(bytes[i]));
    }
    if (tail != 0) acc = churn_word(tail, acc);

    env->ReleaseByteArrayElements(input, bytes, JNI_ABORT);
    return static_cast<jint>(acc);
}
// UNIQUE:NATIVE_STUB:END
